config/routes.rb
Rails.application.routes.draw do
  
  root to: 'events#index'
  get 'events/index'

  resources :events do
    collection { post :import }
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  namespace :admin do
    resources :users
  end
  
  resources :users

end

app/views/shares/_calculator.html.erb
<div class="content">
        <a class="js-modal-open" href="">電卓を使う</a>
    </div>
    <div class="modal js-modal">
        <div class="modal__bg js-modal-close"></div>
        <div class="modal__content">
            <p><div class="calculator">
            <input type="text" id="result">
              <div>
                <input type="button" value="1" onclick="edit(this)">
                <input type="button" value="2" onclick="edit(this)">
                <input type="button" value="3" onclick="edit(this)">
                <input type="button" value="+" onclick="edit(this)">
              </div>
              <div>
                <input type="button" value="4" onclick="edit(this)">
                <input type="button" value="5" onclick="edit(this)">
                <input type="button" value="6" onclick="edit(this)">
                <input type="button" value="-" onclick="edit(this)">
              </div>
              <div>
                <input type="button" value="7" onclick="edit(this)">
                <input type="button" value="8" onclick="edit(this)">
                <input type="button" value="9" onclick="edit(this)">
                <input type="button" value="/" onclick="edit(this)">
              </div>
              <div>
                <input type="button" value="0" onclick="edit(this)">
                <input type="button" value="." onclick="edit(this)">
                <input type="button" value="*" onclick="edit(this)">
                <input type="button" value="=" onclick="calc()">
              </div>
            </div>
          </p>
            <a class="js-modal-close" href="">閉じる</a>
        </div><!--modal__inner-->
    </div>

  <script language="javascript" type="text/javascript">
  var result = document.getElementById("result");
  function edit(elem) {
    result.value = result.value + elem.value;
  }
  function calc() {
    result.value = new Function("return " + result.value)();
  }
</script>

app/views/shares/_edit_delete_btn.html.erb
<div class="edit_delete_btn">
  <% if user_signed_in?  %>
    <span><%= link_to '編集', edit_event_path(events.id), class: 'btn'  %></span>
    <span><%= link_to '削除', event_path(events.id), method: :delete, data:{confirm: "削除してもよろしいですか？"}, class: 'btn' %></span>
  <% end %>
</div>