config/routes.rb
Rails.application.routes.draw do
  
  root to: 'events#index'
  get 'events/index'

  resources :events do
    collection { post :import }
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  namespace :admin do
    resources :users
  end
  
  resources :users

end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user

    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            event = find_by(id: row["id"]) || new
            event.attributes = row.to_hash.slice(*updatable_attributes)
            event.save
        end
    end

    def self.updatable_attributes
        ["title", "description", "start_time", "end_time", "paperworktime", "lessontime", "trainingtime", "worktime", "breaktime", "travel_expenses"]
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit]
  PER = 5

  def index
    @user = User.find_by(params[:id])
    @events = Event.all.page(params[:page]).per(PER)
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to events_url
      flash[:notice] = "#{@event.created_at}を登録しました。"
    else
      render :new
    end

  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "#{@event.created_at}を削除しました。"
    redirect_to events_url
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    flash[:notice] = "#{@event.created_at}を編集しました。"
    redirect_to events_url
  end

  def import
    Event.import(params[:file])
    redirect_to events_url
  end

  private

  def event_params
    params.require(:event).permit(:title, :day, :start_time, :end_time, :worktime, :lessontime, 
    :paperworktime, :trainingtime, :breaktime, :travel_expenses, :description)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="form">
  <%= form_with model: event, local: true do |f| %>
    <div class="event_error">
      <% if event.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <ul>
              <% event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
    </div>
  
      <div class="title">
        <%= f.label :タイトル %>
        <p><%= f.text_field :title %></p>
      </div>
  
      <div class="description">
      <%= f.label :詳細 %>
        <p><%= f.text_area :description %></p>
      </div>

      <div class="day">
        <%= f.label :曜日 %>        
        <p><%= f.select :day, [["月", "月"], ["火", "火"], ["水", "水"], ["木", "木"], ["金", "金"], ["土", "土"], ["日", "日"]], :prompt => "曜日を選択", class: "form-control" %></p>
      </div>
  
      <div class="start_time">
        <%= f.label :開始時間 %>
        <p><%= f.datetime_select :start_time %></p>
      </div>
  
      <div class="end_time">
        <%= f.label :退勤時間 %>
        <p><%= f.datetime_select :end_time %></p>
      </div>
  
      <div class="paperworktime">
        <%= f.label :事務時間 %>
        <p><%= f.number_field	 :paperworktime %></p>
      </div>
  
      <div class="lessontime">
        <%= f.label :授業時間 %>
        <p><%= f.number_field	 :lessontime %></p>
      </div>
  
      <div class="trainingtime">
        <%= f.label :研修時間 %>
        <p><%= f.number_field	 :trainingtime %></p>
      </div>
  
  
      <div class="worktime">
        <%= f.label :勤務時間 %>
        <p><%= f.number_field	 :worktime %></p>
      </div>
  
      <div class="breaktime">
        <%= f.label :休憩時間 %>
        <p><%= f.number_field	 :breaktime %></p>
      </div>
  
      <div class="travel_expenses">
        <%= f.label :交通費 %>
        <p><%= f.number_field	 :travel_expenses %></p>
      </div>
    

      <div class="submit">
        <% if current_page?(new_event_path) %>
          <%= f.submit "登録する" %>
        <% else %>
          <%= f.submit "更新する" %>
        <% end %>
      </div>

  <% end %>

  <p><%= render partial: 'shares/calculator' %></p>
</div>

app/views/events/edit.html.erb
<%= render partial: 'events/form', locals: { event: @event } %>

app/views/events/index.html.erb
<%= month_calendar events: @events do |date, events| %>
    <%= date.day %>

    <% events.each do |events| %>
      <% if user_signed_in? && events.user_id == current_user.id %>
        <div>
          <%= link_to events.title, event_path(events.id) %>
        </div>
      <% end %>
    <% end %>
    
<% end %>

<div class="time">
<h3>各時間</h3>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">曜日</th>
      <th scope="col">開始時間</th>
      <th scope="col">退勤時間</th>
      <th scope="col">事務時間(分)</th>
      <th scope="col">授業時間(分)</th>
      <th scope="col">研修時間(分)</th>
      <th scope="col">勤務時間(分)</th>
      <th scope="col">休憩時間(分)</th>
      <th scope="col">交通費</th>
      <th scope="col">その他</th>
    </tr>
  </thead>
  <tbody>
      <% @events.each do |events| %>
        <% if user_signed_in? && events.user_id == current_user.id %>
        <tr>
          <td><%= events.day %></td>
          <td><%= events.start_time.strftime("%Y-%m-%d  %H:%M") %></td>
          <td><%= events.end_time.strftime("%Y-%m-%d  %H:%M") %></td>
          <td><%= events.paperworktime %></td>
          <td><%= events.lessontime %></td>
          <td><%= events.trainingtime %></td>
          <td><%= events.worktime %></td>
          <td><%= events.breaktime %></td>
          <td><%= events.travel_expenses %></td>
          <td><%= render partial: "shares/edit_delete_btn", locals: { events: events } %></td>          
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
  <%= paginate @events if user_signed_in? %>
  <div class="csv">
  <% if user_signed_in? %>
    <%= link_to "CSV出力", events_path(format: :csv), class: 'btn' %>
    <%= form_tag import_events_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "CSV入力" %>
    <% end %>
  <% end %>
</div>
</div>

app/views/events/new.html.erb
<%= render partial: 'events/form', locals: { event: @event } %>

app/views/events/show.html.erb
<div class="event_show">  
  <table class="table">
  <tbody>
    <tr>
      <th scope="row">タイトル</th>
      <td><%= @event.title %></td>
    </tr>
    <tr>
      <th scope="row">開始時間</th>
      <td><%= @event.start_time %></td>
    </tr>
    <tr>
      <th scope="row">終了時間</th>
      <td><%= @event.end_time %></td>
    </tr>
    <tr>
      <th scope="row">勤務時間</th>
      <td><%= @event.worktime %></td>
    </tr>
    <tr>
      <th scope="row">休憩時間</th>
      <td><%= @event.breaktime %></td>
    </tr>
    <tr>
      <th scope="row">交通費</th>
      <td><%= @event.travel_expenses %></td>
    </tr>
    <tr>
      <th scope="row">詳細</th>
      <td><%= @event.description %></td>
    </tr>
  </tbody>
  </table>
<%= link_to '戻る', events_path, class: 'btn' %>
</div>