config/routes.rb
Rails.application.routes.draw do
  
  root to: 'events#index'
  get 'events/index'

  resources :events do
    collection { post :import }
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  namespace :admin do
    resources :users
  end
  
  resources :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kintaikun</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/events/index">Kintaikun</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
      <%= link_to 'ホーム', events_path, class: 'nav-item nav-link' %>
      <%= link_to 'ログイン', new_user_session_path, class: 'nav-item nav-link' unless user_signed_in? %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-item nav-link' if user_signed_in? %>
      <%= link_to '新規登録', new_user_registration_path, class: 'nav-item nav-link' unless user_signed_in? %>
      <%= link_to 'イベントを登録する', new_event_path, class: 'nav-item nav-link' if user_signed_in? %>
      <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-item nav-link' if user_signed_in? %>
      <%= link_to '管理者画面', admin_users_path, class: 'nav-item nav-link' if current_user.try(:admin?) %>
    </div>
  </div>
</nav>

  <div class="container">

      <% if notice %>
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">close</span>
          </button>
          <%= notice %>
        </div>
      <% end %>

      <% if alert %>
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">close</span>
          </button>
        <%= alert %>
        </div>
      <% end %>

  </div>


    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>